<?php


include 'utils.php';
include 'db.php';
init_db();
checkUser();
checkUserPublic();

$userid = getUserId();



$usr_qry=decode_result(exec_sql("SELECT `fname`,`lname`,`idNumber` FROM  `users` WHERE `userid`= '$userid'"));
$res= decode_result(exec_sql("SELECT * FROM `claims` WHERE `userID` ='$userid' "));








?>
<?php





$imagepath="img/logo.jpg";

require('fpdf.php');
$pdf = new FPDF();
$pdf->AddPage();

//adding a page i.e overriding thefpdf class in fpdf.php  
$pdf->Image($imagepath,80,30,30,0);
$pdf->SetFont('Arial','B',14);	
$pdf->Ln(12);
$pdf->Cell(135,8," ONGATA RONGAI POLICE ABSTRACT " ,0,'C',TRUE);
$pdf->Ln(26);
$pdf->Cell(50,5,"KENYA ",0,'R',TRUE);
$pdf->Cell(90,5,"POLICE ",0,'L',TRUE);
$pdf->Ln(10);
$pdf->SetFont('Arial','B',12);	

$pdf->MultiCell(180,5,"ONGATA RONGAI \n  	POLICE STATION \n P.O. BOX 15664 \n MBAGATHI ",0,'R');
$pdf->Ln();
 
 $pdf->SetFont('Arial','B',14);
 $pdf->Cell(2,3,"",0,'L',FALSE);	
$pdf->Cell(200,3,"----------------------------------------------------------------------------------------------------------",0,'L',FALSE);
$pdf->Ln(10);
 $pdf->Cell(2,3,"",0,'L',FALSE);	
 $pdf->Cell(200,3,"----------------------------------------------------------------------------------------------------------",0,'L',FALSE);
$pdf->Ln(15);
 $pdf->SetFont('Arial','',12);
$pdf->Cell(35,5,"FIRST NAME : ",0,'L',FALSE);

foreach ($usr_qry as $x) {
	 $pdf->SetFont('Arial','B',14);
$pdf->Cell(64,5,$x['fname'],0,'R',FALSE);

	
}
 $pdf->SetFont('Arial','',12);

$pdf->Cell(35,5,"OTHER NAME : ",0,'L',FALSE);
foreach ($usr_qry as $x) {
	 $pdf->SetFont('Arial','B',14);
$pdf->Cell(64,5,$x['lname'],0,'R',FALSE);

	
}
$pdf->Ln(10);
 $pdf->SetFont('Arial','',12);
$pdf->Cell(35,5,"DATE OF LOSS :",0,'L',FALSE);

foreach ($res as $x) {
	
	 $pdf->SetFont('Arial','B',14);

	
$pdf->Cell(64,5,$x['claim_report_date'],0,'R',FALSE);

}

 $pdf->SetFont('Arial','',12);
$pdf->Cell(38,5,"PLACE OF LOSS :",0,'L',FALSE);
foreach ($res as $x) {
	 $pdf->SetFont('Arial','B',14);
$pdf->Cell(64,5,$x['claim_location'],0,'R',FALSE);

	
}
$pdf->Ln(10);
 $pdf->SetFont('Arial','',12);
$pdf->Cell(35,5,"ID NUMBER :",0,'L',FALSE);
foreach ($usr_qry as $x) {
	 $pdf->SetFont('Arial','B',14);
$pdf->Cell(64,5,$x['idNumber'],0,'R',FALSE);

	
}
 $pdf->SetFont('Arial','',12);
$pdf->Cell(90,5,"ISSUING OFFICER :",0,'L',FALSE);
$pdf->Ln(10);
$pdf->SetFont('Arial','B',14);
 $pdf->Cell(2,3,"",0,'L',FALSE);	
$pdf->Cell(200,3,"----------------------------------------------------------------------------------------------------------",0,'L',FALSE);
$pdf->Ln(10);
 $pdf->Cell(2,3,"",0,'L',FALSE);	
 $pdf->Cell(200,3,"----------------------------------------------------------------------------------------------------------",0,'L',FALSE);
$pdf->Ln(10);
$pdf->Cell(150,5,"NOTE:-VALID FOR THREE MONTHS ONLY ",0,'C',TRUE);
$pdf->Ln(14);
$pdf->SetFont('Arial','I',10);
$pdf->Cell(160,5,"this is a digital autogenerated document and hence does not  need to be stampped. ",0,'C',TRUE);
$pdf->Ln(50);
$pdf->SetFont('Arial','b',10);
$pdf->Cell(140,5,"BigFoot Innovations (c) 2016-2017  all right reserved ",0,'C',TRUE);

$pdf->Output();


?>